#pragma once

#define RGB_DISABLE_TIMEOUT 300000
#define RGB_DISABLE_WHEN_USB_SUSPENDED 1
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS 1
#define RGB_MATRIX_TYPING_HEATMAP_DECREASE_DELAY_MS 50

#define TAPPING_TERM 130
